import { useState } from "react";
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { MintWill } from "../services/mint";
import useSWR from 'swr';

export default function Will({ address }) {

    const [state, setState] = useState({
        beneficiary: undefined,
        will_file: undefined,
        unlock_date: undefined,
        tokens: undefined,
      });

    const handleChange = (evt) => {
        const name = evt.target.name;
        const value = (name === "will_file") ? evt.target.files[0] : evt.target.value;
        setState({
          ...state,
          [name]: value,
        });
      };

      const onSubmit = async (e) => {
            MintWill(state);
      };

    return (
        <div className={styles.container}>
            <Head>
                <title>New Will</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo.svg" />
            </Head>

            {!address &&
                <main className={styles.prompt}>
                    <h1 className="mb-4 text-4xl font-extrabold tracking-tight leading-none text-gray-900 md:text-5xl lg:text-6xl dark:text-white">Connect your <span className="text-blue-600 dark:text-blue-500">Hiro Wallet</span></h1>
                </main>
            }

            {address &&
                <main className={styles.main}>
                    <div>
                        <div className="grid gap-6 mb-6 md:grid-cols-2">
                            <div>
                                <label htmlFor="beneficiary" className="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Beneficiary</label>
                                <input name="beneficiary" onChange={handleChange} type="text" id="beneficiary" className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="STYMF4ARBZEVT61CKV8RBQHC6NCGCAF7AQWH979K" required />
                            </div>
                            <div>
                                <label className="block mb-2 text-sm font-medium text-gray-900 dark:text-white" htmlFor="will_file">Upload Will</label>
                                <input name="will_file" onChange={handleChange} id="will_file" type="file" className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required/>
                                <p className="mt-1 text-sm text-gray-500 dark:text-gray-300" id="will_file_help">PNG, JPG or JPEG | 2 MB</p>
                            </div>
                            <div>
                                <label htmlFor="unlock_date" className="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Unlock Date</label>
                                <input name="unlock_date" onChange={handleChange} className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" type="datetime-local" id="unlock_date"/>
                            </div>
                            <div>
                                <label htmlFor="tokens" className="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Giveaway Tokens</label>
                                <input name="tokens" onChange={handleChange} type="number" id="tokens" className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="100 STX" required />
                            </div>
                           
                        </div>
                       
                    
                        <button onClick={onSubmit} className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Mint</button>
                    </div>

                </main>
            }
        </div>
    )
}