import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Digital Wills</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <main className={styles.prompt}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Digital Wills!</a>
        </h1>

        
      </main>

    </div>
  )
}
