import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Wills() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Wills</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <main className={styles.main}>
        

        
      </main>

    </div>
  )
}