import Head from 'next/head'
import styles from '../styles/Home.module.css'
import WillCard from '../components/will'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import useSWR from 'swr';
import { contractDeployerAddress, contractName, assetName, getWillData } from '../libs/stacks/contracts/integration'
import { decryptData } from '../libs/stacks/encryption/symmetric';

const fetcher = (...args) => fetch(...args).then((res) => res.json())
const asset_identifier = `${contractDeployerAddress}.${contractName}::${assetName}`

export default function Wills({ address }) {

  const [wills, setWills] = useState([]);
  const { data, error } = useSWR(address ? `https://stacks-node-api.testnet.stacks.co/extended/v1/tokens/nft/holdings?principal=${address}&asset_identifiers=${asset_identifier}` : null, fetcher, { refreshInterval: 5000 });

  useEffect(() => {

    if (data) {
      if (data.results.length > 0) {
        const my_wills = data.results.map((element) => {
          let id = element.value.repr;
          id = id.slice(1);
          return id;
        })

        const fetchWillData = async () => {

          let will_data = [];

          for (let i = 0; i < my_wills.length; i++) {

            const data = await getWillData(my_wills[i]);

            const cipher = data.url.value.slice(2)

            const url = await decryptData(Buffer.from(cipher, 'hex'))

            will_data.push({ id: my_wills[i], amount: data.amount.value, unlock: new Date(parseInt(data['unlock-time'].value) * 1000), claimed: data.claimed.value, url: url, donor: data.donor.value })
          }

          return will_data;
        }


        fetchWillData().then(value => {
          setWills(value)
        });
      }
    }

  }, [data]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Wills</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      {!address &&
        <main className={styles.prompt}>
          <h1 className="mb-4 text-4xl font-extrabold tracking-tight leading-none text-gray-900 md:text-5xl lg:text-6xl dark:text-white">Connect your <span className="text-blue-600 dark:text-blue-500">Hiro Wallet</span></h1>
        </main>
      }
      {address &&
        <main className={styles.main}>
          <Link
            className='ml-5 text-white bg-gradient-to-r from-green-400 via-green-500 to-green-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-green-300 dark:focus:ring-green-800 font-medium rounded-lg text-xl px-5 py-2.5 text-center mr-2 mb-2'
            href="/create">Create!</Link>

          {wills.length > 0 &&
            <div className="flex flex-wrap justify-between">

              {wills.map((item, index) => (
                <WillCard key={index} id={item.id} donor={item.donor} amount={item.amount} unlock={item.unlock.toLocaleString()}
                  desc="Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order."
                  img={item.url}
                  claimed={item.claimed} />
              ))}

            </div>
          }

          {wills.length == 0 &&
            <div class="text-center">
              <div role="status">
                <svg class="inline mr-2 w-10 h-10 text-gray-200 animate-spin dark:text-gray-600 fill-blue-600" viewBox="0 0 100 101" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z" fill="currentColor" />
                  <path d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z" fill="currentFill" />
                </svg>
                <span class="sr-only">Loading...</span>
              </div>
            </div>
          }
        </main>
      }

    </div>
  )
}