import Head from 'next/head'
import styles from '../styles/Home.module.css'
import WillCard from '../components/will'
import Link from 'next/link'

export default function Wills({ address }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Wills</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      {!address &&
        <main className={styles.prompt}>
          <h1 class="mb-4 text-4xl font-extrabold tracking-tight leading-none text-gray-900 md:text-5xl lg:text-6xl dark:text-white">Connect your <span class="text-blue-600 dark:text-blue-500">Hiro Wallet</span></h1>
        </main>
      }
      {address && 
      <main className={styles.main}>

        <Link
          className='ml-5 text-white bg-gradient-to-r from-green-400 via-green-500 to-green-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-green-300 dark:focus:ring-green-800 font-medium rounded-lg text-xl px-5 py-2.5 text-center mr-2 mb-2'
          href="/create">Create!</Link>


        <div class="flex flex-wrap justify-between">

          <WillCard title="Will Title"
            desc="Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order."
            img="https://flowbite.com/docs/images/blog/image-4.jpg" />

          <WillCard title="Will Title"
            desc="Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order."
            img="https://flowbite.com/docs/images/blog/image-4.jpg" />




        </div>




      </main>
      }

    </div>
  )
}