name: CI
on: [push,pull_request]
jobs:
  job1:
    name: "Test contracts with Clarinet"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Execute test suite"
        uses: docker://hirosystems/clarinet:latest
        with:
          entrypoint: "bash"
          args: -c "cd digital-will/libs/stacks/contracts/digitalWill && clarinet test > log.txt"  
  job2:
    name: "Checking Logs"
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Read log.txt
        id: log
        uses: juliangruber/read-file-action@v1
        with:
          path: ./digital-will/libs/stacks/contracts/digitalWill/log.txt
      - name: Echo log.txt
        run: echo "${{ steps.log.outputs.content }}"
  