name: CI
on: [push,pull_request]
jobs:
  job1:
    name: "Test contracts with Clarinet"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Execute test suite"
      - uses: actions/setup-node@v3
      - uses: docker://hirosystems/clarinet:latest
        with:
          entrypoint: "bash"
          args: -c "npm ci && cd digital-will/libs/stacks/contracts/digitalWill && clarinet test > log.txt && node test"