name: CI
on: [push,pull_request]
jobs:
  job1:
    name: "Test contracts with Clarinet"
    runs-on: ubuntu-latest
    uses: actions/checkout@v3
    steps:
      - name: "Execute test suite"
        uses: docker://hirosystems/clarinet:latest
        id: test-log
        with:
          entrypoint: "bash"
          args: -c "cd digital-will/libs/stacks/contracts/digitalWill && clarinet test"
      - name: "Check logs"
        uses: actions/setup-node@v3
        with:
          node-version: '16'
        run: echo ${{ steps.test-log.outputs.stdout }}