name: CI
on: [push,pull_request]
jobs:
  job1:
    name: "Test contracts with Clarinet"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Execute test suite"
        id: "test-suite"
        uses: docker://hirosystems/clarinet:latest
        with:
          entrypoint: "bash"
          args: -c "cd digital-will/libs/stacks/contracts/digitalWill && clarinet test"
  job2:
    name: "Checking Logs"
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - run: ${{ job1.steps.test-suite.outputs.stdout }}      