name: CI
on: [push,pull_request]
jobs:
  job1:
    name: "Test contracts with Clarinet"
    runs-on: ubuntu-latest
    outputs:
      log: ${{ steps.test-log.outputs.log }}
    steps:
      - uses: actions/checkout@v3
      - name: "Execute test suite"
        uses: docker://hirosystems/clarinet:latest
        id: test-log
        with:
          entrypoint: "bash"
          args: -c "cd digital-will/libs/stacks/contracts/digitalWill && clarinet test"
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - run: echo ${{steps.job1.outputs.log}}