name: CI
on: [push,pull_request]
jobs: 
  test:
    name: "Test contracts with Clarinet"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker://hirosystems/clarinet:latest
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: docker://hirosystems/clarinet:latest
        with:
          entrypoint: "bash"
          args: -c "cd digital-will/libs/stacks/contracts/digitalWill && clarinet test > log.txt"
      - run: npm ci
      - run: "cd digital-will/libs/stacks/contracts/digitalWill && clarinet test > log.txt && node test"