name: CI
on: [push,pull_request]
jobs:
  job1:
    name: "Test contracts with Clarinet"
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - id: step1
      - uses: actions/checkout@v3
      - uses: docker://hirosystems/clarinet:latest
        with:
          entrypoint: "bash"
          args: -c "cd digital-will/libs/stacks/contracts/digitalWill && clarinet test" >> $GITHUB_OUTPUT
  job2:
    name: "Checking Logs"
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}}